inputs:
  version:
    description: "A version to install lambroll"
    default: "v1.0.5"
runs:
  using: "composite"
  steps:
    - name: Set file name
      id: set-filename
      run: |
        BIN_OS=$(case "${{ runner.os }}" in
          Linux) echo "linux" ;;
          macOS) echo "darwin" ;;
          *) echo "linux" ;;
        esac)

        BIN_ARCH=$(case "${{ runner.arch }}" in
          X64) echo "amd64" ;;
          ARM64) echo "arm64" ;;
          *) echo "amd64" ;;
        esac)

        FILENAME=lambroll_${{ inputs.version }}_${BIN_OS}_${BIN_ARCH}.tar.gz
        echo "FILENAME=$FILENAME" >> $GITHUB_OUTPUT
      shell: bash
    - run: |
        mkdir -p /tmp/lambroll-${{ inputs.version }}
        cd /tmp/lambroll-${{ inputs.version }}
        curl -sL https://github.com/fujiwara/lambroll/releases/download/${{ inputs.version }}/${{ steps.set-filename.outputs.FILENAME }} | tar zxvf -
        sudo install lambroll /usr/local/bin
      shell: bash
